stages:
  - pre_check
  - auto_trans
  - build_docs
  - deploy
  - post_links

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_PIPELINE_SOURCE == 'api'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

include:
  - '.gitlab/ci/build_docs.yml'
  - '.gitlab/ci/deploy.yml'
  - '.gitlab/ci/auto_trans.yml'
  - '.gitlab/ci/check_link.yml'
