specified_files:
#development_stage
  - docs/zh_CN/development_stage/rf_test_certification/ce_certification.rst
  - docs/zh_CN/development_stage/rf_test_certification/fcc_certification.rst
  - docs/zh_CN/development_stage/rf_test_certification/srrc_certification.rst
  - docs/zh_CN/development_stage/rf_test_certification/wfa_certification.rst
  - docs/zh_CN/development_stage/rf_test_guide/glossary.rst
  - docs/zh_CN/development_stage/rf_test_guide/rf_test_guide_tool.rst
  - docs/zh_CN/development_stage/rf_test_guide/version.rst
  - docs/zh_CN/development_stage/rf_test_items/ble_adaptivity_test.rst
  - docs/zh_CN/development_stage/rf_test_items/ble_blocking_test.rst
  - docs/zh_CN/development_stage/rf_test_items/ble_dtm_test.rst
  - docs/zh_CN/development_stage/rf_test_items/rf_non_signalling_test.rst
  - docs/zh_CN/development_stage/rf_test_items/wfa_certification_test.rst
  - docs/zh_CN/development_stage/rf_test_items/wifi_adaptivity_test.rst
  - docs/zh_CN/development_stage/rf_test_items/wifi_blocking_test.rst
  - docs/zh_CN/development_stage/rf_test_items/wifi_signalling_test.rst

#faq
  - docs/zh_CN/faq/ble_adaptivity_test_faq.rst
  - docs/zh_CN/faq/ble_blocking_test_faq.rst
  - docs/zh_CN/faq/ble_dtm_test_faq.rst
  - docs/zh_CN/faq/esp_rf_test_guide_tool_faq.rst
  - docs/zh_CN/faq/flash_download_tool_faq.rst
  - docs/zh_CN/faq/rf_non_signalling_test_faq.rst
  - docs/zh_CN/faq/wfa_certification_test_faq.rst
  - docs/zh_CN/faq/wifi_adaptivity_test_faq.rst
  - docs/zh_CN/faq/wifi_blocking_test_faq.rst
  - docs/zh_CN/faq/wifi_signalling_test_faq.rst

#get-started
  - docs/zh_CN/get-started/index.rst

#production_stage
  - docs/zh_CN/production_stage/instructions/test_fixture_mfg_inst.rst
  - docs/zh_CN/production_stage/tools/esp_production_testing_guide/esp_production_testing_guide.rst
  - docs/zh_CN/production_stage/tools/esp_production_testing_guide/glossary.rst
  - docs/zh_CN/production_stage/tools/esp_production_testing_guide/version.rst
  - docs/zh_CN/production_stage/tools/flash_download_tool/flash_download_tool.rst
  - docs/zh_CN/production_stage/tools/flash_download_tool/glossary.rst
  - docs/zh_CN/production_stage/tools/flash_download_tool/version.rst
  - docs/zh_CN/production_stage/tools/matter_qr_code_generator/matter_qr_code_generator.rst
  - docs/zh_CN/production_stage/tools/matter_qr_code_generator/glossary.rst
  - docs/zh_CN/production_stage/tools/matter_qr_code_generator/version.rst

#copyright
  - docs/zh_CN/copyright.rst

#resources
  - docs/zh_CN/resources.rst

target_language: EN-CN

trans_dict:
  firmware: 固件

target_language_folder: ./