specified_files:
#development_stage
#  - docs/zh_CN/development_stage/rf_test_certification/ce_certification.rst
  - docs/zh_CN/development_stage/rf_test_certification/fcc_certification.rst
#  - docs/zh_CN/development_stage/rf_test_certification/srrc_certification.rst
#  - docs/zh_CN/development_stage/rf_test_certification/wfa_certification.rst
#  - docs/zh_CN/development_stage/rf_test_guide/glossary.rst
#  - docs/zh_CN/development_stage/rf_test_guide/rf_bin_list.rst
#  - docs/zh_CN/development_stage/rf_test_guide/rf_test_guide_tool.rst
#  - docs/zh_CN/development_stage/rf_test_guide/version.rst
#  - docs/zh_CN/development_stage/rf_test_items/ble_adaptivity_test.rst
#  - docs/zh_CN/development_stage/rf_test_items/ble_blocking_test.rst
#  - docs/zh_CN/development_stage/rf_test_items/ble_dtm_test.rst
#  - docs/zh_CN/development_stage/rf_test_items/bt_ble_non_signaling_test.rst
#  - docs/zh_CN/development_stage/rf_test_items/wfa_certification_test.rst
#  - docs/zh_CN/development_stage/rf_test_items/wifi_adaptivity_test.rst
#  - docs/zh_CN/development_stage/rf_test_items/wifi_blocking_test.rst
#  - docs/zh_CN/development_stage/rf_test_items/wifi_non_signaling_test.rst
#  - docs/zh_CN/development_stage/rf_test_items/wifi_signaling_test.rst
#  - docs/zh_CN/development_stage/rf_test_items/zigbee_non_signaling_test.rst

#faq
#  - docs/zh_CN/faq/ble_adaptivity_test_faq.rst
#  - docs/zh_CN/faq/ble_blocking_test_faq.rst
#  - docs/zh_CN/faq/ble_dtm_test_faq.rst
#  - docs/zh_CN/faq/esp_rf_test_guide_tool_faq.rst
#  - docs/zh_CN/faq/flash_download_tool_faq.rst
#  - docs/zh_CN/faq/rf_non_signaling_test_faq.rst
#  - docs/zh_CN/faq/wfa_certification_test_faq.rst
#  - docs/zh_CN/faq/wifi_adaptivity_test_faq.rst
#  - docs/zh_CN/faq/wifi_blocking_test_faq.rst
#  - docs/zh_CN/faq/wifi_signaling_test_faq.rst

#get-started
#  - docs/zh_CN/get-started/index.rst

#production_stage
#  - docs/zh_CN/production_stage/instructions/test_fixture_mfg_inst.rst
#  - docs/zh_CN/production_stage/tools/esp_production_testing_guide/esp_production_testing_guide.rst
#  - docs/zh_CN/production_stage/tools/esp_production_testing_guide/glossary.rst
#  - docs/zh_CN/production_stage/tools/esp_production_testing_guide/version.rst
#  - docs/zh_CN/production_stage/tools/flash_download_tool/flash_download_tool.rst
#  - docs/zh_CN/production_stage/tools/flash_download_tool/glossary.rst
#  - docs/zh_CN/production_stage/tools/flash_download_tool/version.rst
#  - docs/zh_CN/production_stage/tools/matter_qr_code_generator/matter_qr_code_generator.rst
#  - docs/zh_CN/production_stage/tools/matter_qr_code_generator/glossary.rst
#  - docs/zh_CN/production_stage/tools/matter_qr_code_generator/version.rst

#introduction
#  - docs/zh_CN/index.rst

#copyright
#  - docs/zh_CN/copyright.rst

#resources
#  - docs/zh_CN/resources.rst

target_language: EN-CN

trans_dict:
  Wi-Fi Non-Signaling Test: Wi-Fi 非信令测试
  Wi-Fi Signaling Test: Wi-Fi 信令测试
  Wi-Fi Adaptivity Test: Wi-Fi 自适应测试
  Wi-Fi Blocking Test: Wi-Fi 接收阻塞测试
  Bluetooth/Bluetooth LE Non-Signaling Test: 蓝牙/低功耗蓝牙非信令测试
  Bluetooth LE DTM Test: 低功耗蓝牙 DTM 测试
  Bluetooth LE Adaptivity Test: 低功耗蓝牙自适应测试
  Bluetooth LE Blocking Test: 低功耗蓝牙阻塞测试
  802.15.4 Non-Signaling Test: 802.15.4 非信令测试
  Bluetooth: 蓝牙
  Bluetooth LE: 低功耗蓝牙

target_language_folder: ./